swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:          
  /transaction/{idTransaction}:
    post:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Add a comment 
      description: allow the adding of a comment on a transaction
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          type: string
          required: true
        - name: idTransaction
          in: path
          required: true
          type: integer
          description: id transaction
        - name: transaction
          in: body
          description: comment payload.
          required: true
          schema:
           $ref: '#/definitions/Transaction'
      produces:
        - application/json 
      responses:
        '201':
          description: comment adding successully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put: 
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Edit a comment 
      description: allow the edit of a comment on a transaction
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          type: string
          required: true
        - name: idTransaction
          in: path
          required: true
          type: integer
          description: id transaction
        - name: transaction
          in: body
          description: comment payload.
          required: true
          schema:
           $ref: '#/definitions/Transaction'
      produces:
        - application/json 
      responses:
        '201':
          description: comment edited successully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    delete: 
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Delet a comment 
      description: delet a comment on a transaction
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          type: string
          required: true
        - name: idTransaction
          in: path
          required: true
          type: integer
          description: id transaction
      produces:
        - application/json 
      responses:
        '201':
          description: comment deleted successully
          schema: 
           $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error    
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: get a specific transaction 
      description: get info from on a transaction
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          type: string
          required: true
        - name: idTransaction
          in: path
          required: true
          type: integer
          description: id transaction
      produces:
        - application/json 
      responses:
        '200':
          description: get a specific transaction successully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transaction:
    type: object
    properties:
      id: 
        type: integer
        example: 3
      date: 
        type: string
        example: 2023-09-22 16:25:20
      description: 
        type: string
        example: "Ceci est un commentaire."
      amount: 
        type: integer
        example: 320
      creditor: 
         type: string
      comment:
        type: string
