swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: User Accounts API
      description: API for fetching user's accounts
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Accounts data retrieved successully
          schema:
            $ref: "#/definitions/UserAccounts"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized, missing or invalid Bearer token
        "403":
          description: Forbidden. The client does not have access rights to the content
        "500":
          description: Internal Server Error

  /accounts/{accountID}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: User Account Transactions API
      description: API for fetching current month account transactions
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - name: accountID
          in: path
          type: string
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Transactions data retrieved successully
          schema:
            $ref: "#/definitions/AccountTransactions"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized, missing or invalid Bearer token
        "403":
          description: Forbidden. The client does not have access rights to the content
        "500":
          description: Internal Server Error

  /accounts/{accountID}/transactions/{transactionID}:
    put:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Update transaction details API
      description: API for updating / deleting notes or category details of a specific transaction. To delete a category / note provide a null value in body
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - name: accountID
          in: path
          type: string
          required: true
        - name: transactionID
          in: path
          type: string
          required: true
        - in: body
          name: body
          description: Transaction details to update
          required: true
          schema:
            $ref: "#/definitions/TransactionUpdate"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction updated successully
          schema:
            $ref: "#/definitions/UpdateTransactionAPIResponse"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized, missing or invalid Bearer token
        "403":
          description: Forbidden. The client does not have access rights to the content
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  UserAccounts:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            userID:
              type: string
            accountID:
              type: string
            accountType:
              type: string
            balance:
              type: integer
            balanceType:
              type: string
  AccountTransactions:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            transactionID:
              type: string
            date:
              type: string
              description: transaction date
            description:
              type: string
              description: transaction description
            amount:
              type: integer
              description: transaction account
            balance:
              type: integer
              description: amount balance
            transactionType:
              type: string
              description: transaction type
            category:
              type: string
              description: transaction category
            notes:
              type: string
              description: transaction related notes
  TransactionUpdate:
    type: object
    properties:
      category:
        type: string
        description: transaction category
      notes:
        type: string
        description: transaction related notes
  UpdateTransactionAPIResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          transactionID:
            type: string
          date:
            type: string
            description: transaction date
          description:
            type: string
            description: transaction description
          amount:
            type: integer
            description: transaction account
          balance:
            type: integer
            description: amount balance
          transactionType:
            type: string
            description: transaction type
          category:
            type: string
            description: transaction category
          notes:
            type: string
            description: transaction related notes
