swagger: '2.0'
info:
  title: Documentation de l'API Bank Argent
  description: Contient tous les endpoints d'API disponibles dans cette base de code
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - Module Utilisateur
      summary: Connexion
      description: API pour la connexion
      parameters:
        - in: body
          name: body
          description: Données de connexion
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Connexion réussie
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Champs invalides
        '500':
          description: Erreur serveur interne
  /user/signup:
    post:
      tags:
        - Module Utilisateur
      summary: Inscription
      description: API pour l'inscription
      parameters:
        - in: body
          name: body
          description: Données d'inscription
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Inscription réussie
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Champs invalides
        '500':
          description: Erreur serveur interne
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - Module Utilisateur
      summary: API Profil Utilisateur
      description: API pour récupérer le profil utilisateur
      parameters:
        - in: header
          name: Authorization
          description: Joindre le token JWT Bearer
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Profil utilisateur récupéré avec succès
          schema:
            $ref: '#/definitions/UserProfileResponse'
        '400':
          description: Champs invalides
        '500':
          description: Erreur serveur interne
    put:
      security:
        - Bearer: []
      tags:
        - Module Utilisateur
      summary: API Profil Utilisateur
      description: API pour mettre à jour le profil utilisateur
      parameters:
        - in: header
          name: Authorization
          description: Joindre le token JWT Bearer
          required: true
        - in: body
          name: body
          description: Mettre à jour les attributs du profil utilisateur
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: Profil utilisateur mis à jour avec succès
          schema:
            $ref: '#/definitions/UserProfileResponse'
        '400':
          description: Champs invalides
        '500':
          description: Erreur serveur interne
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    type: object
    properties:
      email:
        type: string
        description: Adresse e-mail de l'utilisateur
      password:
        type: string
        description: Mot de passe de l'utilisateur
      firstName:
        type: string
        description: Prénom de l'utilisateur
      lastName:
        type: string
        description: Nom de famille de l'utilisateur
      userName:
        type: string
        description: Nom public de l'utilisateur
  Login:
    type: object
    properties:
      email:
        type: string
        description: Adresse e-mail de l'utilisateur
      password:
        type: string
        description: Mot de passe de l'utilisateur
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
        description: Jeton d'autorisation
  UserProfile:
    type: object
    properties:
      userName:
        type: string
        description: Nom public de l'utilisateur
  UserProfileResponse:
    type: object
    properties:
      profile:
        type: object
        properties:
          id:
            type: string
            description: ID unique de l'utilisateur
          email:
            type: string
            description: Adresse e-mail de l'utilisateur
          firstName:
            type: string
            description: Prénom de l'utilisateur
          lastName:
            type: string
            description: Nom de famille de l'utilisateur
          userName:
            type: string
            description: Nom public de l'utilisateur
